# Método SIMPLEX

In [1]:
import numpy as np
import sys

In [33]:
def print_matriz(matriz, qtd_linha, qtd_coluna):
    for i in range(qtd_linha):
        for j in range(qtd_coluna):
            print(matriz[i][j], end=" ")

        print()

### Pegando quantidade de variáveis

In [183]:
qtd_var_obj = int(input("Quantas variáveis tem a função objetivo? \n"))

Quantas variáveis tem a função objetivo? 
 3


In [185]:
qtd_res_des = int(input("Quantas restrições com desigualdade? \n"))

Quantas restrições com desigualdade? 
 4


In [187]:
lista_var = []

for i in range(qtd_var_obj+1, (qtd_var_obj + qtd_res_des)+1):
    lista_var.append(i)

lista_var = np.array(lista_var)

lista_var

array([4, 5, 6, 7])

### Pegando matriz

In [196]:
mat = []

while True:
    linha = input("Digite uma linha (ou \"p\" para parar) \n")

    if linha.lower() == "p": #condição de parada
        break

    linha = linha.split()

    try:
        linha = [float(x) for x in linha] #cast para float
    except ValueError:
        print("Insira apenas números ou \"p\" para parar \n")
        continue

    mat.append(linha)

Digite uma linha (ou "p" para parar) 
 2 2 4 1 0 0 0 300
Digite uma linha (ou "p" para parar) 
 0 4 3 0 1 0 0 200
Digite uma linha (ou "p" para parar) 
 1 0 0 0 0 1 0 20
Digite uma linha (ou "p" para parar) 
 4 3 0 0 0 0 1 50
Digite uma linha (ou "p" para parar) 
 -10 -20 -30 0 0 0 0 0
Digite uma linha (ou "p" para parar) 
 p


In [198]:
matriz = np.array(mat)

In [200]:
matriz

array([[  2.,   2.,   4.,   1.,   0.,   0.,   0., 300.],
       [  0.,   4.,   3.,   0.,   1.,   0.,   0., 200.],
       [  1.,   0.,   0.,   0.,   0.,   1.,   0.,  20.],
       [  4.,   3.,   0.,   0.,   0.,   0.,   1.,  50.],
       [-10., -20., -30.,   0.,   0.,   0.,   0.,   0.]])

### Realizando cálculos

In [203]:
qtd_linha = len(matriz)
qtd_linha

5

In [204]:
qtd_coluna = len(matriz[0])

qtd_coluna

8

In [207]:
ultima_linha = matriz[qtd_linha-1]

ultima_linha

array([-10., -20., -30.,   0.,   0.,   0.,   0.,   0.])

In [209]:
while len([*filter(lambda x: x < 0, ultima_linha)]) > 0:
    menor = min(ultima_linha)

    for i in range(qtd_coluna): 
        if ultima_linha[i] == menor:
            coluna_pivo = i

    aux_m = 2 * sys.maxsize + 1
    linha_pivo = -1
    
    for i in range(qtd_linha-1):
        e = matriz[i][coluna_pivo]
    
        if e != 0:
            f = matriz[i][qtd_coluna-1] / e
    
            if f < aux_m:
                aux_m = f
                linha_pivo = i
                
    lista_var[linha_pivo] = coluna_pivo + 1

    matriz[linha_pivo] = matriz[linha_pivo] / matriz[linha_pivo][coluna_pivo]

    for i in range(qtd_linha):
        if i != linha_pivo:
            matriz[i] = matriz[i] - (matriz[i][coluna_pivo] * matriz[linha_pivo])

[4 3 6 1]
0.0 -4.833333333333333 0.0 1.0 -1.3333333333333333 0.0 -0.5 8.333333333333314 
0.0 1.3333333333333333 1.0 0.0 0.3333333333333333 0.0 0.0 66.66666666666667 
0.0 -0.75 0.0 0.0 0.0 1.0 -0.25 7.5 
1.0 0.75 0.0 0.0 0.0 0.0 0.25 12.5 
0.0 27.5 0.0 0.0 10.0 0.0 2.5 2125.0 


### Mostrando resultados

In [219]:
#print(lista_var)
print_matriz(matriz, qtd_linha, qtd_coluna)

0.0 -4.833333333333333 0.0 1.0 -1.3333333333333333 0.0 -0.5 8.333333333333314 
0.0 1.3333333333333333 1.0 0.0 0.3333333333333333 0.0 0.0 66.66666666666667 
0.0 -0.75 0.0 0.0 0.0 1.0 -0.25 7.5 
1.0 0.75 0.0 0.0 0.0 0.0 0.25 12.5 
0.0 27.5 0.0 0.0 10.0 0.0 2.5 2125.0 


In [217]:
for i in range(len(lista_var)):
    print(f"x{lista_var[i]} = {matriz[i][qtd_coluna-1]}")

print()
print(f"z = {matriz[qtd_linha-1][qtd_coluna-1]}")

x4 = 8.333333333333314
x3 = 66.66666666666667
x6 = 7.5
x1 = 12.5

z = 2125.0


### Rascunho

In [10]:
menor = min(ultima_linha)

menor

-30.0

In [11]:
for i in range(qtd_coluna): 
    if ultima_linha[i] == menor:
        coluna_pivo = i

coluna_pivo

2

In [12]:
aux_m = 2 * sys.maxsize + 1
linha_pivo = -1

for i in range(qtd_linha-1):
    e = matriz[i][coluna_pivo]

    if e != 0:
        f = matriz[i][qtd_coluna-1] / e

        if f < aux_m:
            aux_m = f
            linha_pivo = i
        
        
print(aux_m, linha_pivo)

66.66666666666667 1


In [13]:
matriz[linha_pivo] = matriz[linha_pivo] / matriz[linha_pivo][coluna_pivo]

matriz[linha_pivo]

array([ 0.        ,  1.33333333,  1.        ,  0.        ,  0.33333333,
        0.        ,  0.        , 66.66666667])

In [37]:
print_matriz(matriz, qtd_linha, qtd_coluna)

2.0 2.0 4.0 1.0 0.0 0.0 0.0 300.0 
0.0 1.3333333333333333 1.0 0.0 0.3333333333333333 0.0 0.0 66.66666666666667 
1.0 0.0 0.0 0.0 0.0 1.0 0.0 20.0 
4.0 3.0 0.0 0.0 0.0 0.0 1.0 50.0 
-10.0 -20.0 -30.0 0.0 0.0 0.0 0.0 0.0 


In [41]:
for i in range(qtd_linha):
    if i != linha_pivo:
        matriz[i] = matriz[i] - (matriz[i][coluna_pivo] * matriz[linha_pivo])

In [43]:
print_matriz(matriz, qtd_linha, qtd_coluna)

2.0 -3.333333333333333 0.0 1.0 -1.3333333333333333 0.0 0.0 33.333333333333314 
0.0 1.3333333333333333 1.0 0.0 0.3333333333333333 0.0 0.0 66.66666666666667 
1.0 0.0 0.0 0.0 0.0 1.0 0.0 20.0 
4.0 3.0 0.0 0.0 0.0 0.0 1.0 50.0 
-10.0 20.0 0.0 0.0 10.0 0.0 0.0 2000.0000000000002 


In [73]:
a = np.array([0, 25, 0, 0, 10, 0, 2.5, 2125])

In [75]:
print(len([*filter(lambda x: x < 0, a)]) > 0)

False
